"""1st revision

Revision ID: 38036612433b
Revises: 
Create Date: 2024-05-15 14:54:56.721894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '38036612433b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modelrun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model_input_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model_output_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('openaimodelrun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prompt_template', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('transplant_organ', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('diagnosis_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('classification', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('explanation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('probability_within_90_days', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('openai_call_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('system_fingerprint', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prompt_tokens', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('completion_tokens', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_tokens', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userindb',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userindb')
    op.drop_table('openaimodelrun')
    op.drop_table('modelrun')
    # ### end Alembic commands ###
